### ISSUE TITLE
Votekey generation fails on insertion to database

### ISSUE THREAD

**Issue by argasek** [Gargaj/wuhu#8]
Hi,

After clicking 'Generate new!' I get:

```
Fatal error: Uncaught exception 'Exception' with message '<pre> MySQL ERROR: Query: insert votekeys (`votekey`) values ('RWXTTLYBPL')
Error: Field 'userid' doesn't have a default value' in /Users/argasek/Sites/www_admin/sqllib.inc.php:23
Stack trace:
#0 /Users/argasek/Sites/www_admin/sqllib.inc.php(61): SQLLib::Query('insert votekeys...')
#1 /Users/argasek/Sites/www_admin/votekeys.php(16): SQLLib::InsertRow('votekeys', Array)
#2 {main} thrown in /Users/argasek/Sites/www_admin/sqllib.inc.php on line 23
```

**Comment by Gargaj** [comment]
Odd, I'll look into it.

**Comment by Gargaj** [comment]
Out of curiousity, what DB are you using?

**Comment by argasek** [comment]
Thanks. Will provide details as soon as I get home. :)

**Comment by argasek** [comment]
```
argasek@lorelai ~ $ mysql --version
mysql  Ver 14.14 Distrib 5.6.22, for osx10.9 (x86_64) using  EditLine wrapper
argasek@lorelai ~ $ php --version
PHP 5.4.40 (cli) (built: May  3 2015 22:07:42) 
```

**Comment by Gargaj** [comment]
Hm, might be the 5.6-ness. I'll fix it in a second.

**Comment by Gargaj** [comment]
(You might need to manually update your database.)

**Comment by argasek** [comment]
Awesome. Will test in the evening. Thank you! :)
